name: "Build"
on:
  push:
    # Only run on branches
    branches:
    - '**'

permissions:
  id-token: write
  pages: write


jobs:
  browser:
    runs-on: ubuntu-22.04
    steps:

    - name: "Checkout emsdk"
      uses: actions/checkout@v4
      with:
        repository: 'emscripten-core/emsdk'
        path: emsdk

    - name: "Checkout brogue"
      uses: actions/checkout@v4
      with:
        path: brogue

    - name: "Compile"
      run: |
        emsdk/emsdk install latest
        emsdk/emsdk activate latest
        source emsdk/emsdk_env.sh
        cd brogue
        ./emscripten_build.sh

    - name: "Upload static files as artifact"
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: brogue/bin/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: browser
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4