name: "Build"
on:
  push:
    # Only run on branches
    branches:
    - '**'

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: "Install dependencies"
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: "Checkout sources"
      uses: actions/checkout@v3

    - name: "Compile"
      run: |
        emscripten_build.sh

    - name: "Upload static files as artifact"
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: bin/
