name: "Build"
on:
  push:
    # Only run on branches
    branches:
    - '**'

jobs:
  browser:
    runs-on: ubuntu-22.04
    steps:

    - name: "Checkout emsdk"
      uses: actions/checkout@v4
      with:
        repository: 'emscripten-core/emsdk.git'
        path: emsdk

    - name: "Checkout brogue"
      uses: actions/checkout@v4
      with:
        path: brogue

    - name: "Compile"
      run: |
        emsdk/emsdk install latest
        emsdk/emsdk activate latest
        source emsdk/emsdk_env.sh
        ./emscripten_build.sh

    - name: "Upload static files as artifact"
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: bin/
